on: push
name: Coverage
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug

      - name: Set-up Composer
        uses: php-actions/composer@v6

      - name: Run tests and collect coverage
        run: ./vendor/bin/phpunit tests --coverage-clover coverage.xml .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
